name: me_poupe
description: aplicacao financeira

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.0
  date_format: ^1.0.8
  flutter_localizations:
    sdk: flutter
  # image
  image_picker: ^0.6.0+3

  # icones
  material_design_icons_flutter: ^4.0.5755
  font_awesome_flutter: ^8.2.0

  # campos mascarados
  brasil_fields: ^0.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/porco_01.png"
  image_path_android: "assets/images/porco_01.png"
  adaptive_icon_background: "assets/images/icone/background.png"
  adaptive_icon_foreground: "assets/images/icone/foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/vida_quadrada.png
    - assets/images/porco_01.png
    - assets/images/plugue.png
    - assets/images/logo_google.png
    - assets/images/logo_face.png
    - assets/images/logo_facebook.png
    - assets/images/user.png
    - assets/images/cartoes_normal.png
    - assets/images/cartoes_escuro.png
    - assets/images/cofre_normal.png
    - assets/images/cofre_escuro.png

    - assets/images/bancos/logo/00.png
    #    - assets/images/bancos/logo/01.png
    - assets/images/bancos/logo/01.png
    - assets/images/bancos/logo/02.png
    - assets/images/bancos/logo/03.png
    - assets/images/bancos/logo/04.png
    - assets/images/bancos/logo/05.png
    - assets/images/bancos/logo/06.png
    - assets/images/bancos/logo/07.png
    - assets/images/bancos/logo/08.png
    - assets/images/bancos/logo/09.png
    - assets/images/bancos/logo/10.png
    - assets/images/bancos/logo/16.png
    - assets/images/bancos/logo/22.png
    - assets/images/bancos/logo/32.png
    - assets/images/bancos/logo/44.png
    - assets/images/bancos/logo/46.png
    - assets/images/bancos/logo/52.png
    - assets/images/bancos/logo/54.png
    - assets/images/bancos/logo/67.png
    - assets/images/bancos/logo/80.png
    # - assets/images/porco_02.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
