import 'package:me_poupe/model/cad/cad_banco_model.dart';

class BancoDummy{
  List<BancoCadModel> get lista {
    return [
      // BancoCadModel( id: 1, descricao:"Minha Carteira" , corPrimaria: "#000000" , corSecundaria: "#FFFFFF",imageAsset: "assets/images/bancos/logo/01.png"),
      BancoCadModel( id: 1, descricao:"ABC Brasil" , corPrimaria: "#000000" , corSecundaria: "#FFFFFF",imageAsset: "assets/images/bancos/logo/01.png"),
      BancoCadModel( id: 2, descricao:"Acesso Bank" , corPrimaria: "#888888" , corSecundaria: "#FFFFFF",imageAsset: "assets/images/bancos/logo/02.png"),
      BancoCadModel( id: 3, descricao:"AgiBank" , imageAsset: "assets/images/bancos/logo/04.png"),
      BancoCadModel( id: 4, descricao:"Amazonia" , imageAsset: "assets/images/bancos/logo/05.png"),
      BancoCadModel( id: 5, descricao:"American Express" ,corPrimaria: "#FFFFFF", corSecundaria: "#016FD0",imageAsset: "assets/images/bancos/logo/05.png"),
      BancoCadModel( id: 6, descricao:"Americanas" ,corCartao:"#E70017" , corPrimaria: "#FFFFFF" , corSecundaria: "#E70017",imageAsset: "assets/images/bancos/logo/06.png"),
      BancoCadModel( id: 7, descricao:"Aura" ,imageAsset: "assets/images/bancos/logo/07.png" ),
      BancoCadModel( id: 8, descricao:"BMG" ,corSecundaria: "#FF6300",imageAsset: "assets/images/bancos/logo/08.png" ),
      BancoCadModel( id: 9, descricao:"BRB" ,imageAsset: "assets/images/bancos/logo/09.png" ),
      BancoCadModel( id: 10, descricao:"BRDE" ,imageAsset: "assets/images/bancos/logo/10.png" ),
      BancoCadModel( id: 11, descricao:"BS2" , ),
      BancoCadModel( id: 12, descricao:"Banco Cacique" , ),
      BancoCadModel( id: 13, descricao:"Banco Inter" , ),
      BancoCadModel( id: 14, descricao:"Banco Pan" , ),
      BancoCadModel( id: 15, descricao:"Banco Votorantim" , ),
      BancoCadModel( id: 16, descricao:"Banco do Brasil" ,destaque: true ,corPrimaria: "#1A5DAD" ,corSecundaria: "#FFF200" ,corCartao: "#D2AB01", ordemDestaque: 10, imageAsset: "assets/images/bancos/logo/16.png"),
      BancoCadModel( id: 17, descricao:"Banco do Nordeste" , ),
      BancoCadModel( id: 18, descricao:"Banese" , ),
      BancoCadModel( id: 19, descricao:"Banestes" , ),
      BancoCadModel( id: 20, descricao:"Banif" , ),
      BancoCadModel( id: 21, descricao:"Banpara" , ),
      BancoCadModel( id: 22, descricao:"Banrisul",destaque: true,corPrimaria: "#016ABE",corSecundaria: "#DBBFD", corTerciaria: "#FFFFFF", corCartao: "#016FAC",ordemDestaque: 20 ,imageAsset: "assets/images/bancos/logo/22.png"),
      BancoCadModel( id: 23, descricao:"Bbm" , ),
      BancoCadModel( id: 24, descricao:"Bradesco" , ),
      BancoCadModel( id: 25, descricao:"C6 Bank" , ),
      BancoCadModel( id: 26, descricao:"Caixa Econômica Federal",destaque: true,corPrimaria: "#296FA7" , corSecundaria: "#F39A00" ,corTerciaria: "#FFFFFF", corCartao: "#296FA7",ordemDestaque: 90,apelido: "Caixa",imageAsset: "assets/images/bancos/logo/32.png"),
      BancoCadModel( id: 27, descricao:"Caju" , ),
      BancoCadModel( id: 28, descricao:"Carrefour" , ),
      BancoCadModel( id: 29, descricao:"Cetelem" , ),
      BancoCadModel( id: 30, descricao:"Citibank" , ),
      BancoCadModel( id: 31, descricao:"Credicard" , ),
      BancoCadModel( id: 32, descricao:"Cruzeirodosul" , ),
      BancoCadModel( id: 33, descricao:"Daycoval" , ),
      BancoCadModel( id: 34, descricao:"Desjardins Bank" , ),
      BancoCadModel( id: 35, descricao:"Digi+" , ),
      BancoCadModel( id: 36, descricao:"Digio" , ),
      BancoCadModel( id: 37, descricao:"Diners" , ),
      BancoCadModel( id: 38, descricao:"EbanxGo" , ),
      BancoCadModel( id: 39, descricao:"Elo" , ),
      BancoCadModel( id: 40, descricao:"Fortbrasil" , ),
      BancoCadModel( id: 41, descricao:"HSBC" , ),
      BancoCadModel( id: 42, descricao:"Havan" , ),
      BancoCadModel( id: 43, descricao:"Hipercard" ),
      BancoCadModel( id: 44, descricao:"Itau" , destaque: true ,corCartao:"#999278" ,corPrimaria: "#FFE512",corSecundaria: "#004990",corTerciaria: "#EF761B" ,ordemDestaque: 30,imageAsset: "assets/images/bancos/logo/44.png"),
      BancoCadModel( id: 45, descricao:"Mais" , ),
      BancoCadModel( id: 46, descricao:"Mastercard" , corPrimaria: "#FFFFFF",corCartao: "#896936", ordemDestaque: 40,imageAsset: "assets/images/bancos/logo/46.png"),
      BancoCadModel( id: 47, descricao:"Mercantil do Brasil" , ),
      BancoCadModel( id: 48, descricao:"Méliuz" , ),
      BancoCadModel( id: 49, descricao:"N26" , ),
      BancoCadModel( id: 50, descricao:"Neon" , ),
      BancoCadModel( id: 51, descricao:"Next" , ),
      BancoCadModel( id: 52, descricao:"Nubank" , destaque: true , corPrimaria: "#FFFFFF",corSecundaria: "#8A05BE" , corCartao:"#8A05BE" ,ordemDestaque: 50,imageAsset: "assets/images/bancos/logo/52.png" ),
      BancoCadModel( id: 53, descricao:"Original" , ),
      BancoCadModel( id: 54, descricao:"Outros" , destaque: true , corPrimaria: "#FFFFFF",corSecundaria: "#CCCCCC", ordemDestaque: 900,imageAsset: "assets/images/bancos/logo/54.png"),
      BancoCadModel( id: 55, descricao:"Pag" , ),
      BancoCadModel( id: 56, descricao:"PagBank" , ),
      BancoCadModel( id: 57, descricao:"PagSeguro" , ),
      BancoCadModel( id: 58, descricao:"PicPay" , ),
      BancoCadModel( id: 59, descricao:"Porto Seguro" , ),
      BancoCadModel( id: 60, descricao:"Safra" , ),
      BancoCadModel( id: 61, descricao:"Satander" , ),
      BancoCadModel( id: 62, descricao:"Senff" , ),
      BancoCadModel( id: 63, descricao:"Shoptime" , ),
      BancoCadModel( id: 64, descricao:"Sicoob" , ),
      BancoCadModel( id: 65, descricao:"Sicredi" , ),
      BancoCadModel( id: 66, descricao:"Social Bank" , ),
      BancoCadModel( id: 67, descricao:"Sodexo",corPrimaria: "#2A295C",corSecundaria: "#7E82D5", corTerciaria: "#FFFFFF", corCartao: "#2A295C",imageAsset: "assets/images/bancos/logo/67.png"),
      BancoCadModel( id: 68, descricao:"Sofisa Direto" , ),
      BancoCadModel( id: 69, descricao:"Submarino" , ),
      BancoCadModel( id: 70, descricao:"Superdigital" , ),
      BancoCadModel( id: 71, descricao:"Trigg" , ),
      BancoCadModel( id: 72, descricao:"Tudo Azul" , ),
      BancoCadModel( id: 73, descricao:"Unicred" , ),
      BancoCadModel( id: 74, descricao:"Uniprime" , ),
      BancoCadModel( id: 75, descricao:"UrPay" , ),
      BancoCadModel( id: 76, descricao:"Viacredi" , ),
      BancoCadModel( id: 77, descricao:"Visa" , ),
      BancoCadModel( id: 78, descricao:"Vitreo" , ),
      BancoCadModel( id: 79, descricao:"Wirecard"),
      BancoCadModel( id: 80, descricao:"GreenCard" ,corPrimaria: "#35764D",corSecundaria: "#8CC8A0", corTerciaria: "#FFFFFF", corCartao: "#8CC8A0",imageAsset: "assets/images/bancos/logo/80.png"),
    ];
  }

}